### ISSUE TITLE
Support multiple triggers

### ISSUE THREAD

**Issue by brunchboy** [brunchboy/beat-link-trigger#2]
The easiest way to do this would be to add a menu option which opens a new trigger window.

If there is time to get fancy, store the current window configuration using Java preferences, so that when you quit and reopen the program, your windows are recreated with their configurations. But since it gets messy if a player is not visible when you try to re-create a window that was supposed to use it, and I am not sure how useful the saved configuration would be anyway, get the menu option working first.

**Comment by drummerclint** [comment]
Not a big deal, but instead of multiple windows popping up, is it possible to expand the window vertically and have another set of fields in the same window?  Each set of fields could have a - button to kill that particular instance and and a + next to the last one to create another deck instance.  Again, this is more of an aesthetic thing and keeps window management under control.  Here's an example from Pro Tools:
http://audiotuts.s3.amazonaws.com/382_protools/CreateNewMultTracks.png
