### ISSUE TITLE
Testing the software whit out connecting cdj ? ( Maybe whit rekordbox)

### ISSUE THREAD

**Issue by bukarti88** [brunchboy/beat-link-trigger#22]
Can we test the software whit out connecting any cdj becouse i cant have my cdjs at my office always also when i export the tracks from rekordbox i cant see the track id s on the software thanks :)

**Comment by brunchboy** [comment]
You need an active DJ Link network in order to really do significant testing. You can choose to work in offline mode when you do not have one available, and at least work on setting up your triggers and expressions, but you won’t be able to actually test them. The network can consist of CDJs, mixers, and XDJs, as long as they support DJ Link. You *might* be able to use rekordbox on a different computer, I have not tested that. You can’t use it on the same computer, because it needs to use the same network ports as beat-link does.

You will need to figure out what the track ID numbers are for each track on each different media database that you export to. The goal of accessing and displaying track title and artist information reliably has not yet been figured out by anyone. If you can contribute to that research, please read the packet analysis paper in the [dysentery](https://github.com/brunchboy/dysentery) project and see where we have gotten stuck.
