### ISSUE TITLE
Exception during creation of metadata cache

### ISSUE THREAD

**Issue by aftermathematic** [brunchboy/beat-link-trigger#32]
Got an exception while trying to create metadata cache... Duplicate entry it says, but no idea what exactly is duplicate.

<img width="1022" alt="screen shot 2017-10-07 at 21 19 49" src="https://user-images.githubusercontent.com/3603311/31311119-b3853dfe-aba5-11e7-95dc-2008daa60080.png">
<img width="548" alt="screen shot 2017-10-07 at 21 19 23" src="https://user-images.githubusercontent.com/3603311/31311120-b38b59d2-aba5-11e7-9a6d-eccabf21010f.png">

**Comment by brunchboy** [comment]
Hmm, I am guessing the problem is that the same track appeared more than once in a playlist? This is Java’s zip file library complaining that we are trying to create a metadata entry for multiple tracks with recordbox ID 70. I would have thought I protected against that, but perhaps not. I will have to take a look at the metadata cache building code in Beat Link and see if I can understand how it happened and fix it. Which will require new releases of both Beat Link and Beat Link Trigger. Thanks for the report!

**Comment by brunchboy** [comment]
I’m mentoring at a hackathon tonight but I had a moment to look at the Beat Link code, and you have definitely found a problem. If a track appears more than once in a playlist, this will happen. It’s an easy fix, and I should hopefully be able to get that done tomorrow. Thanks for opening this!

**Comment by brunchboy** [comment]
I was able to reproduce this problem by ignoring the warning in rekordbox and adding a duplicate track to a playlist. I am testing a hardened version of the Beat Link library now to verify that it fixes the issue.

**Comment by aftermathematic** [comment]
It was indeed a duplicate track in my playlist... I have a 1 second track called "==========" that I use as a visual divider in my playlists which was causing the exception.

**Comment by brunchboy** [comment]
And you should be able to do things like that! It just didn’t occur to me in the rush of getting the caching mechanism working initially. It’s better now. 😄
