### ISSUE TITLE
XDJ Compatibility? 

### ISSUE THREAD

**Issue by InfamousUK** [brunchboy/beat-link-trigger#33]
Does this app work with the link feature on the Pioneer XDJ-700s? As, I have carried out research and it seems that the link/prolink features and protocols are the same, if so, any help as to why beat-link-trigger can not detect them?

**Comment by brunchboy** [comment]
This would be a great thing to research and implement if you can. I don’t have any XDJ hardware, and so will not be able to help. I would start by getting a deep understanding of the protocol via the [dysentery](https://github.com/brunchboy/dysentery) project, studying the packet analysis document, gaining experience with a network capture tool, and using a spanned port on a managed switch to analyze what is different about the XDJs and CDJs, and propose the needed changes to dysentery and the beat-link library.

**Comment by jine** [comment]
Here's a wireshark pcap between an XDJ-RX and Rekordbox (without any beat-link-trigger, as it hangs it - confirmed by a friend of mine aswell)

[XDJ-RX-Pioneer-link-Rekordbox.zip](https://github.com/brunchboy/beat-link-trigger/files/1520176/XDJ-RX-Pioneer-link-Rekordbox.zip)

**Comment by jine** [comment]
Would really love a Wireshark-analyzer for this tho...

**Comment by brunchboy** [comment]
I’m sorry, I’m not going to be able to do anything with this remotely. Thanks for investigating, but it’s going to take someone who has local access to both the XDJ-RX and dysentery / BLT to sit down and analyze exactly what the differences are, and figure out how to fix it. (If anyone is local to Madison, WI and wants to bring their XDJ-RX over some weekend when I have some time available, that could work too.)

**Comment by jine** [comment]
I do have access to both, but I unfortunately live i Stockholm, Sweden. Feel free to visit us if you want? Can invite you to Stockholm Makerspace for a hacknight someday ;)

Anything we can do remotely otherwise?

**Comment by brunchboy** [comment]
I love Stockholm, but I don’t get to visit nearly as often as I’d like! (I lived there for four years when I was a small boy, though. 😄)

If you are willing to investigate it, what I would recommend is studying the dysentery [packet analysis](https://github.com/brunchboy/dysentery/blob/master/doc/Analysis.pdf) document (it is easier to read if you download the raw PDF and use a local viewer or print it) to get a grounding in what we understand of the protocol so far, then look at captures of what is happening right before the RX crashes, in terms of the protocol. I would not be surprised if it turns out to be an issue with the shortcuts we take during the startup/registration process, which might require a more complete implementation of that stage. We have sample code in the [libpdjl](https://bitbucket.org/awwright/libpdjl) implementation we can use as a starting point if that turns out to be true, but I don’t want to spend time doing that if it turns out to be something else.

So, the first step is to find out what the message is that is crashing the RX, then we can focus our attention on how to address that.

**Comment by brunchboy** [comment]
Another possibility is that the RX does not like the fact that Beat Link Trigger does not offer a database server of its own, nor a media server. If that is the problem, we would have to implement a fake database and media server that reported an empty media library, which would be rather tedious. This would probably show up as attempts by the RX to connect to the service query port (12523) on the computer running BLT right before the crash (as described in the second paragraph of Section 5: Track Metadata in the packet analysis paper).

**Comment by brunchboy** [comment]
And I’d love it if someone wrote a Wireshark-analyzer for this stuff! That would be a great contribution. 😄

**Comment by jine** [comment]
I'll check what I can do ;) No promises tho!

**Comment by brunchboy** [comment]
No promises were assumed! But sadly, I have just discovered this effort is doomed. Pioneer does not support the use of the XDJ-RX with CDJs:

> The LINK on the RX is ONLY for linking to rekordbox on your computer or a router with WiFi to connect rekordbox mobile. It can not exchange LINK data with other CDJs or DJMs.

https://forums.pioneerdj.com/hc/en-us/community/posts/203113059-xdj-rx-as-single-deck-on-pro-dj-link-

In other words, the XDJ-RX does not actually implement the Pro DJ Link protocol. Since beat-link emulates a CDJ, there is no way this is ever going to work.

**Comment by InfamousUK** [comment]
This is not for the use with the XDJ-RX, in my case it is for the use of the XDJ-700 (Its a multi-player like the CDJs but does not take CDs). I would like to use these instead of controllers so that my laptop can be dedicated to other processes. As you can see, the XDJ-700 and XDJ-1000 (MK1 and MK2) both have the pro link features.

http://faq.pioneerdj.com/product.php?lang=en&p=XDJ-700&t=355

Please reopen this as I am going to be testing them and analysing them with in the next few days/weeks.

**Comment by brunchboy** [comment]
Ah, sorry, OK I have reopened it for you. My understanding is that people have successfully used BLT with XDJ-1000s, I don’t know about the 700 though. I look forward to hearing what you discover.

**Comment by InfamousUK** [comment]
That's cool man, can you link me to BLT?

**Comment by brunchboy** [comment]
Sorry about the confusion; BLT is Beat Link Trigger, in other words, this very project.

**Comment by InfamousUK** [comment]
True aha, I did not think about it

**Comment by InfamousUK** [comment]
I have come back to report that the Pioneer XDJ 700 Multi-Players are indeed compatible with beat-link-trigger. I did not have to do find specific packets as it was a firewall issue with me, it works stand alone. I was wondering if you can help me out with something else, the carabiner project is released for mac? How can I get this on windows?

**Comment by brunchboy** [comment]
Thanks for confirming this, I appreciate it. As far as the Carabiner question goes, I will answer it in more depth over in that project where you also asked, but in short, find someone (perhaps yourself?) who uses Windows and who is willing to build and release it?
