### ISSUE TITLE
open Player Status window on start of app

### ISSUE THREAD

**Issue by aftermathematic** [brunchboy/beat-link-trigger#37]
Is there a way to force the Player Status window to open together with BLT itself when I start it?
It happens to me all the time that I forget I need to open the Player Status window in order to get my timing right. Until I open that window the sync is a bit "off". 

Or is it in any way possible to it not being necessary to open the Player Status window to get the timing  right?

**Comment by brunchboy** [comment]
I am not sure what you mean by “get the timing right.” Ordinary sync operations that most people perform do not require the Player Status window. What is it exactly that you are doing? If you are trying to do something like tie another system to the virtual timecode that BLT can estimate for you (for example by sending Song Position Pointers), then you do need to start the `TimeFinder` which is something that happens when the Player Status window is opened. But I think you could also just start that yourself in the Global Setup expression, with the understanding that it might fail if the environment doesn’t support it (for example, no players can be found).

Because of the fact that the Player Status window requires a much more aggressive interrogation of the players than most Beat Link Trigger use, I am not comfortable with the idea of it opening automatically. People who are not using metadata because they have DJs using four actual players, and who don’t need metadata for their shows, would run into problems.

With that said, there is a hacky way that you can do what you want… Just add the following form to your Global Setup Expression, and when the Trigger window loads, it will also try to open the Player Status Window. It does this the same way as when you choose that option in the menu, so you will get all the necessary error dialogs and coaching if the environment isn’t correct to support the window:

```clojure
(seesaw.core/invoke-later (@#'beat-link-trigger.triggers/show-player-status nil))
```

**Comment by brunchboy** [comment]
I’ve just updated the [preview release](https://github.com/brunchboy/beat-link-trigger/releases/download/v0.3.7/beat-link-trigger-0-3-8-PREVIEW.jar) I’m working on for you to expose a version of the `show-player-status` function that is safe to call from expressions, and easier to access. Instead of the above (which won’t work after you update to the next preview release), you should instead use this simpler form:

```clojure
(beat-link-trigger.triggers/show-player-status)
```

Let me know if this works for you!

**Comment by aftermathematic** [comment]
By the timing being "off" I meant that when I use BLT in conjunction with the MTC-generating app (or your SMPTE generator), the timing is not correct when I play a song, meaning that when I start the song, the timecode doesn't start from the beginning, but continues from where it left off in the previous song.
Once I open the player status window, the problem is gone. 

By the way, I just discovered that when I load a track (but not press play yet) on my player, the play-head in the player status window jumps through all the cue's in the song, before returning to the beginning of the song. An activation and deactivaton expression is also triggered. Since the outgoing midi note in the activation and deactivation expression are midi mapped to the solo button on an Ableton track, I noticed that by loading a track on the player, the ableton track swiftly got solo'd and un-solo'd.
It's possible that the activation and deactivation occur because of a badly written expression by me, but I'm quite surprised the playhead jumps through the whole song from cue to cue before returning to the beginning. I noticed it because there are multiple cue's in most of my songs. This all happens in a matter of 1 to 2 seconds.

Have you come across this behaviour before?

**Comment by brunchboy** [comment]
Right, that’s what I was talking about. Trying to fake timecode (such as using MTC or my SMPTE proof of concept) goes beyond what the DJ Link protocol actually supports, and is outside the normal use of Beat Link Trigger. For that to work, you need to have the `TimeFinder` running, a piece of code in Beat Link that watches traffic from the players and keeps a running guess of what point has been reached in the track. This can only be a guess, since the only definitive information we receive are the packets sent when each beat is reached, and we can interpolate with some error-correction with the help of intervening status packets. But that requires loading a lot more information from the players, such as the full track beat grid, and most users don’t need that.

What you are seeing with the playhead jumping is something I have seen too. My best guess is that in order to prepare itself for instantly jumping to any hot cues in the track, it needs to pre-flight the entire track when it loads it, and cache the sections immediately following the cues into RAM, and that for some reason it reports its position in the track as it does that.

With respect to your activation and deactivation, you are probably right, the expression is probably not exactly correct. You are doing things that are so complicated that I think you’re going to need to study the exact details of the protocol packets sent by the players (in the Packet Analysis article in the dysentery project), and carefully design your logic.

**Comment by brunchboy** [comment]
Although if the Activation expression runs, is there _any_ player playing? If not, I would not expect that to happen. Are you sure there is not code in some other expression of yours that is sending MIDI? Or perhaps the player actually briefly reports itself to be playing, which would be even more annoying. You would need to get a network traffic capture to diagnose that.
