### ISSUE TITLE
track speed / position question

### ISSUE THREAD

**Issue by aftermathematic** [brunchboy/beat-link-trigger#38]
Hi, I'm still in talks with a guy who is making a Max For Live app that generates Midi Timecode based on BeatLinkTrigger.

He wants to know if BLT is sending a continuous stream of song speed (as in normaal speed + pitch adjustment) and song position of which his app can calculate the correct midi timecode. The reason why he asks is because right now only song speed is sent when the song is started, which means that when a song has a loop in it, the timecode will run out of sync.

As we've discussed before, the objective is still to have Ableton run in perfect sync with my CDJ players, be it in EXT mode or LINK mode doesn't matter to me.

Do you have any insights on what speed/position/... info is available which he can use to generate the correct Midi timecode?

**Comment by brunchboy** [comment]
This question doesn’t really make sense to me, I’m afraid. BLT doesn’t send anything except what you tell it to, so if you need that information, you will have to send it from your code in your expressions. There was a fairly detailed discussion of how to do exactly this with Ableton a few weeks ago in the Gitter chat, including code that showed how to detect loops and react to them. I’d like to flesh out that example a bit and add it to the User Guide, or perhaps the Wiki, but have been far too busy at work for the past several weeks to do that. So for now the chat is your best bet.

It sounds like this guy needs to spend some time really studying the Beat Link Trigger [User Guide](https://github.com/brunchboy/beat-link-trigger/blob/master/doc/README.adoc#beat-link-trigger-user-guide), and perhaps the underlying Beat Link documentation, to understand exactly what is possible and how. I even have an example in there of how to use a Max application to generate time code (in my case, SMPTE rather than MTC), but your developer friend should follow the same approach in managing his communication between BLT and his Max application. If he does that, he can take advantage of all the work my Beat Link `TimeFinder` class does in detecting and managing loops, and translating those into time information. Look for the “SMPTE Linear Timecode” example in the User Guide, and study the Max application and Trigger configuration I link to there.

**Comment by brunchboy** [comment]
We made great progress turning these ideas into a really deep integration between CDJs and Ableton Live. It deserves a writeup in the Wiki!
